version: "3"
services:
  db:
    image: mysql:latest
    container_name: situs-forum
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=situs-forum-db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
